module MyPrelude.RestrictedClassyPrelude
  ( module X,
  )
where

import ClassyPrelude as X hiding
  ( bracket,
    bracketOnError,
    bracket_,
    catch,
    catchDeep,
    catchIO,
    catchJust,
    catches,
    catchesDeep,
    evaluate,
    evaluateDeep,
    finally,
    handle,
    handleDeep,
    handleIO,
    handleJust,
    isAsyncException,
    isSyncException,
    mask,
    mask_,
    onException,
    readFile,
    readFileUtf8,
    throwIO,
    try,
    tryDeep,
    tryIO,
    tryJust,
    uninterruptibleMask,
    uninterruptibleMask_,
    writeFile,
    writeFileUtf8,
  )
